Tarea calculadora
grunger94/design-patterns pull request #8
Opened 2018-07-13 01:38 UTC by manueltopt96

a ver qué tal

2018-07-13 01:52 UTC, grunger94 requested changes

2018-07-13 01:52 UTC, grunger94 commented on manuel/template/Multiplicacion.php
> +			// return $this->valor1 - $this->valor2;
Eliminar codigo comentado que no se usa

2018-07-13 01:52 UTC, grunger94 commented on manuel/template/Division.php
> +            return $enFraccion;
Aqui es donde estas sobreescribiendo el comportamiento de la clase abstracta, retorna true aqui y elimina public $enFraccion = true;

2018-07-13 01:52 UTC, grunger94 commented on manuel/template/Multiplicacion.php
> +			$valor1 = $this->valor1;
No necesitas las variables $valor1 y $valor2

2018-07-13 01:52 UTC, grunger94 commented on manuel/template/Division.php
> +                $valor1 = $this->valor1;
Eliminar $valor1 y $valor2, puedes usar los argumentos originales porque no los estas modificando en ningun momento

2018-07-13 15:30 UTC, grunger94 requested changes

2018-07-13 15:30 UTC, grunger94 commented on manuel/template/Division.php
> +        public $enFraccion;
Esta variable deberia vivir en Operacion y podria ser protegida o privada con un metodo setter

2018-07-13 15:30 UTC, grunger94 commented on manuel/template/Operacion.php
> +        protected function setValores($valor1, $valor2)
Tu aplicacion solo accede a la funcion ejecuta() desde fuera, los metodos que se usan solo de manera local dentro de esta clase pueden ser privados

2018-07-13 15:32 UTC, manueltopt96 commented on manuel/template/Division.php
> +        public $enFraccion;
okay, entonces la pongo protegida en Operacion y le hago un setter en Division?

2018-07-13 15:33 UTC, manueltopt96 commented on manuel/template/Operacion.php
> +        protected function setValores($valor1, $valor2)
okay, entonces lo dejo en privado

2018-07-13 16:05 UTC, grunger94 commented on manuel/template/Operacion.php
> +        private function enFraccion()
Tu hook debe ser protected o no sera alcanzable por las subclases

2018-07-16 23:02 UTC, manueltopt96 commented on manuel/template/Operacion.php
> +        private function enFraccion()
ya lo puse como protected

2018-07-17 15:56 UTC, grunger94 approved these changes

2018-07-17 15:56 UTC, merged